"""add statistics

Revision ID: 0ee5f2f3f53a
Revises: 3f6f5f10f211
Create Date: 2026-01-22 13:05:05.054016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0ee5f2f3f53a'
down_revision: Union[str, Sequence[str], None] = '3f6f5f10f211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('total_rental_count', sa.Integer(), nullable=False),
    sa.Column('average_rental_duration', sa.Float(), nullable=False),
    sa.Column('recent_rental_count', sa.Integer(), nullable=False),
    sa.Column('recent_avg_duration', sa.Float(), nullable=False),
    sa.Column('unique_borrower_count', sa.Integer(), nullable=False),
    sa.Column('last_borrowed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.drop_column('assets', 'status')
    op.add_column('schedule', sa.Column('club_id', sa.Integer(), nullable=False))
    op.add_column('schedule', sa.Column('status', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'schedule', 'club', ['club_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_column('schedule', 'status')
    op.drop_column('schedule', 'club_id')
    op.add_column('assets', sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('statistics')
    # ### end Alembic commands ###
