"""add club location info

Revision ID: 1b79008a3b1d
Revises: 0ee5f2f3f53a
Create Date: 2026-01-22 15:58:17.533405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b79008a3b1d'
down_revision: Union[str, Sequence[str], None] = '0ee5f2f3f53a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('location_lat', sa.Integer(), nullable=True))
    op.add_column('club', sa.Column('location_lng', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club', 'location_lng')
    op.drop_column('club', 'location_lat')
    # ### end Alembic commands ###
