"""add schedule.status, schedule.club_id, delete asset.status

Revision ID: 263b8bc8921d
Revises: 3f6f5f10f211
Create Date: 2026-01-19 18:29:27.695294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '263b8bc8921d'
down_revision: Union[str, Sequence[str], None] = '3f6f5f10f211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'status')
    op.add_column('schedule', sa.Column('club_id', sa.Integer(), nullable=False))
    op.add_column('schedule', sa.Column('status', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'schedule', 'club', ['club_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_column('schedule', 'status')
    op.drop_column('schedule', 'club_id')
    op.add_column('assets', sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
