"""assets.category_id nullable로 변경

Revision ID: 3f6f5f10f211
Revises: 44e7b9789956
Create Date: 2026-01-19 07:13:16.262536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3f6f5f10f211'
down_revision: Union[str, Sequence[str], None] = '44e7b9789956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
