"""picture update

Revision ID: 402464aa8488
Revises: 1b79008a3b1d
Create Date: 2026-01-27 11:02:28.523015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '402464aa8488'
down_revision: Union[str, Sequence[str], None] = '1b79008a3b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('asset_id', sa.Integer(), nullable=False))
    op.add_column('picture', sa.Column('data', sa.LargeBinary().with_variant(mysql.LONGBLOB(), 'mysql'), nullable=False))
    op.add_column('picture', sa.Column('content_type', sa.String(length=50), nullable=False))
    op.add_column('picture', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('picture', sa.Column('size', sa.Integer(), nullable=False))
    op.alter_column('picture', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('picture_ibfk_1'), 'picture', type_='foreignkey')
    op.create_foreign_key(None, 'picture', 'assets', ['asset_id'], ['id'])
    op.drop_column('picture', 'assets_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('assets_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'picture', type_='foreignkey')
    op.create_foreign_key(op.f('picture_ibfk_1'), 'picture', 'assets', ['assets_id'], ['id'])
    op.alter_column('picture', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('picture', 'size')
    op.drop_column('picture', 'filename')
    op.drop_column('picture', 'content_type')
    op.drop_column('picture', 'data')
    op.drop_column('picture', 'asset_id')
    # ### end Alembic commands ###
