"""add social connect info

Revision ID: 55604aa7c297
Revises: 8564cc51791c
Create Date: 2026-02-02 17:35:22.178734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55604aa7c297'
down_revision: Union[str, Sequence[str], None] = '8564cc51791c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('social_linked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'social_linked_at')
    # ### end Alembic commands ###
