"""add schedule.status, schedule.club_id

Revision ID: 60513fd58cb7
Revises: 44e7b9789956
Create Date: 2026-01-17 22:06:17.112453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60513fd58cb7'
down_revision: Union[str, Sequence[str], None] = '44e7b9789956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('club_id', sa.Integer(), nullable=False))
    op.add_column('schedule', sa.Column('status', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'schedule', 'club', ['club_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_column('schedule', 'status')
    op.drop_column('schedule', 'club_id')
    # ### end Alembic commands ###
