"""add return picture

Revision ID: 8564cc51791c
Revises: f3b777c853f6
Create Date: 2026-02-02 17:14:14.509048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8564cc51791c'
down_revision: Union[str, Sequence[str], None] = 'f3b777c853f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('return_picture_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'schedule', 'picture', ['return_picture_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_column('schedule', 'return_picture_id')
    # ### end Alembic commands ###
