"""ver4

Revision ID: 9e1ff39517d0
Revises: 47a99100431f
Create Date: 2026-01-09 17:26:42.706794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1ff39517d0'
down_revision: Union[str, Sequence[str], None] = '47a99100431f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('picture_id', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('status', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'assets', 'picture', ['picture_id'], ['id'])
    op.add_column('club', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('club', sa.Column('club_code', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'club', ['club_code'])
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('student_id', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'student_id')
    op.drop_column('user', 'is_admin')
    op.drop_constraint(None, 'club', type_='unique')
    op.drop_column('club', 'club_code')
    op.drop_column('club', 'description')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'status')
    op.drop_column('assets', 'picture_id')
    # ### end Alembic commands ###
