"""increase_hashed_password_length

Revision ID: dd9d143cef40
Revises: 55604aa7c297
Create Date: 2026-02-04 17:35:28.148470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dd9d143cef40'
down_revision: Union[str, Sequence[str], None] = '55604aa7c297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###
