"""add max_rental_days to asset

Revision ID: f3b777c853f6
Revises: 402464aa8488
Create Date: 2026-02-01 07:49:34.870521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b777c853f6'
down_revision: Union[str, Sequence[str], None] = '402464aa8488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('max_rental_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'max_rental_days')
    # ### end Alembic commands ###
